/**
 * Enumeration of all possible Tebex error codes.
 * Consumers can use these codes to provide localized error messages.
 */
export enum TebexErrorCode {
  // Provider errors (1xx)
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  INVALID_CONFIG = 'INVALID_CONFIG',

  // Authentication errors (2xx)
  NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
  INVALID_USERNAME = 'INVALID_USERNAME',

  // Basket errors (3xx)
  BASKET_NOT_FOUND = 'BASKET_NOT_FOUND',
  BASKET_CREATION_FAILED = 'BASKET_CREATION_FAILED',
  BASKET_EXPIRED = 'BASKET_EXPIRED',
  BASKET_EMPTY = 'BASKET_EMPTY',

  // Package errors (4xx)
  PACKAGE_NOT_FOUND = 'PACKAGE_NOT_FOUND',
  PACKAGE_OUT_OF_STOCK = 'PACKAGE_OUT_OF_STOCK',
  PACKAGE_ALREADY_OWNED = 'PACKAGE_ALREADY_OWNED',
  INVALID_QUANTITY = 'INVALID_QUANTITY',

  // Category errors (5xx)
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  // Coupon/GiftCard errors (6xx)
  COUPON_INVALID = 'COUPON_INVALID',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  COUPON_ALREADY_USED = 'COUPON_ALREADY_USED',
  GIFTCARD_INVALID = 'GIFTCARD_INVALID',
  GIFTCARD_INSUFFICIENT_BALANCE = 'GIFTCARD_INSUFFICIENT_BALANCE',
  CREATOR_CODE_INVALID = 'CREATOR_CODE_INVALID',

  // Checkout errors (7xx)
  CHECKOUT_FAILED = 'CHECKOUT_FAILED',
  CHECKOUT_CANCELLED = 'CHECKOUT_CANCELLED',
  TEBEX_JS_NOT_LOADED = 'TEBEX_JS_NOT_LOADED',

  // Network errors (8xx)
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  RATE_LIMITED = 'RATE_LIMITED',

  // Unknown
  UNKNOWN = 'UNKNOWN',
}
